// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace NServiceKit.Funq.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NServiceKit.Funq.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ResolutionException_MissingType {
            get {
                return ResourceManager.GetString("ResolutionException_MissingType", resourceCulture);
            }
        }
        
        internal static string Registration_CantRegisterContainer {
            get {
                return ResourceManager.GetString("Registration_CantRegisterContainer", resourceCulture);
            }
        }
        
        internal static string ResolutionException_MissingNamedType {
            get {
                return ResourceManager.GetString("ResolutionException_MissingNamedType", resourceCulture);
            }
        }
        
        internal static string ResolutionException_UnknownScope {
            get {
                return ResourceManager.GetString("ResolutionException_UnknownScope", resourceCulture);
            }
        }
        
        internal static string Registration_IncompatibleAsType {
            get {
                return ResourceManager.GetString("Registration_IncompatibleAsType", resourceCulture);
            }
        }
    }
}
