SET NUGET=..\src\.nuget\nuget
%NUGET% push NServiceKit.3.9.60.nupkg
%NUGET% push NServiceKit.3.9.60.symbols.nupkg
%NUGET% push NServiceKit.Api.Swagger.3.9.60.nupkg
%NUGET% push NServiceKit.Api.Swagger.3.9.60.symbols.nupkg
%NUGET% push NServiceKit.Authentication.OAuth2.3.9.60.nupkg
%NUGET% push NServiceKit.Authentication.OAuth2.3.9.60.symbols.nupkg
%NUGET% push NServiceKit.Authentication.OpenId.3.9.60.nupkg
%NUGET% push NServiceKit.Authentication.OpenId.3.9.60.symbols.nupkg
%NUGET% push NServiceKit.Client.Silverlight.3.9.60.nupkg
%NUGET% push NServiceKit.Common.3.9.60.nupkg
%NUGET% push NServiceKit.Common.3.9.60.symbols.nupkg
%NUGET% push NServiceKit.Host.AspNet.3.9.60.nupkg
%NUGET% push NServiceKit.Host.Mvc.3.9.60.nupkg
%NUGET% push NServiceKit.Mvc.3.9.60.nupkg
%NUGET% push NServiceKit.Mvc.3.9.60.symbols.nupkg
%NUGET% push NServiceKit.Plugins.MsgPack.3.9.60.nupkg
%NUGET% push NServiceKit.Plugins.MsgPack.3.9.60.symbols.nupkg
%NUGET% push NServiceKit.Plugins.ProtoBuf.3.9.60.nupkg
%NUGET% push NServiceKit.Plugins.ProtoBuf.3.9.60.symbols.nupkg
%NUGET% push NServiceKit.Razor.3.9.60.nupkg
%NUGET% push NServiceKit.Razor.3.9.60.symbols.nupkg
