using System;
using System.Diagnostics;
using System.IO;
using NServiceKit.Logging;

namespace NServiceKit.Razor.Managers
{
    /// <summary>Interface for live reload.</summary>
    public interface ILiveReload
    {
        /// <summary>Starts a watching.</summary>
        ///
        /// <param name="scanRootPath">Full pathname of the scan root file.</param>
        void StartWatching(string scanRootPath);
    }

    /// <summary>A file system watcher live reload.</summary>
    public class FileSystemWatcherLiveReload : ILiveReload
    {
        /// <summary>The log.</summary>
        public static ILog Log = LogManager.GetLogger(typeof(FileSystemWatcherLiveReload));

        /// <summary>
        /// The purpose of the FileSystemWatcher is to ensure razor pages are
        /// consistent with the code generated by the razor engine. The file
        /// system watcher will invalidate pages and queue them for recompilation.
        /// </summary>
        protected FileSystemWatcher FileSystemWatcher;
        private readonly RazorViewManager views;

        /// <summary>Initializes a new instance of the NServiceKit.Razor.Managers.FileSystemWatcherLiveReload class.</summary>
        ///
        /// <param name="views">The views.</param>
        public FileSystemWatcherLiveReload(RazorViewManager views)
        {
            this.views = views;
        }

        /// <summary>Starts a watching.</summary>
        ///
        /// <param name="scanRootPath">Full pathname of the scan root file.</param>
        public void StartWatching(string scanRootPath)
        {
            //setup the file system watcher for page invalidation
            this.FileSystemWatcher = new FileSystemWatcher(scanRootPath, "*.*")
                {
                    IncludeSubdirectories = true,
                    EnableRaisingEvents = true,
                    //NotifyFilter = NotifyFilters.CreationTime | NotifyFilters.FileName | NotifyFilters.LastWrite
                };

            this.FileSystemWatcher.Changed += FileSystemWatcher_Changed;
            this.FileSystemWatcher.Created += FileSystemWatcher_Created;
            this.FileSystemWatcher.Deleted += FileSystemWatcher_Deleted;
            this.FileSystemWatcher.Renamed += FileSystemWatcher_Renamed;
            this.FileSystemWatcher.Error += FileSystemWatcher_Error;
        }

        /// <summary>
        /// Avoid throwing unhandled exception when shutting down ASP.NET host
        /// </summary>
        private void FileSystemWatcher_Error(object sender, ErrorEventArgs e)
        {
            Log.WarnFormat("FileSystemWatcher Error: ", sender);
        }

        /// <summary>Event handler. Called by FileSystemWatcher for renamed events.</summary>
        ///
        /// <param name="sender">Source of the event.</param>
        /// <param name="e">     Renamed event information.</param>
        protected virtual void FileSystemWatcher_Renamed(object sender, RenamedEventArgs e)
        {
            try
            {
                var oldPagePath = views.GetDictionaryPagePath(views.GetRelativePath(e.OldFullPath));

                if (!views.Pages.Remove(oldPagePath))
                {
                    //Debugger.Break();
                }

                views.AddPage(e.FullPath);
            }
            catch (Exception ex)
            {
                Log.Warn("FileSystemWatcher_Renamed error: ", ex);
            }
        }

        /// <summary>Event handler. Called by FileSystemWatcher for deleted events.</summary>
        ///
        /// <param name="sender">Source of the event.</param>
        /// <param name="e">     File system event information.</param>
        protected virtual void FileSystemWatcher_Deleted(object sender, FileSystemEventArgs e)
        {
            try
            {
                var file = views.GetVirutalFile(e.FullPath);
                if (file == null || !views.IsWatchedFile(file)) return;

                var pathPage = views.GetDictionaryPagePath(file);

                views.Pages.Remove(pathPage);
            }
            catch (Exception ex)
            {
                Log.Warn("FileSystemWatcher_Deleted error: ", ex);
            }
        }

        /// <summary>Event handler. Called by FileSystemWatcher for created events.</summary>
        ///
        /// <param name="sender">Source of the event.</param>
        /// <param name="e">     File system event information.</param>
        protected virtual void FileSystemWatcher_Created(object sender, FileSystemEventArgs e)
        {
            try
            {
                views.AddPage(e.FullPath);
            }
            catch (Exception ex)
            {
                Log.Warn("FileSystemWatcher_Created error: ", ex);
            }
        }

        /// <summary>Event handler. Called by FileSystemWatcher for changed events.</summary>
        ///
        /// <param name="sender">Source of the event.</param>
        /// <param name="e">     File system event information.</param>
        protected virtual void FileSystemWatcher_Changed(object sender, FileSystemEventArgs e)
        {
            try
            {
                var file = views.GetVirutalFile(e.FullPath);
                if (file == null || !views.IsWatchedFile(file)) return;

                var pagePath = views.GetDictionaryPagePath(file);

                RazorPage page;
                if (views.Pages.TryGetValue(pagePath, out page))
                    views.InvalidatePage(page);
            }
            catch (Exception ex)
            {
                Log.Warn("FileSystemWatcher_Changed error: ", ex);
            }
        }
    }
}
